apiVersion: v1
kind: ConfigMap
metadata:
  name: git-sync-config
  namespace: airflow-dev
data:
  GITSYNC_REPO: https://github.com/21voidx/Airflow-k8s-dags-gitsync.git
# sementara
  GITSYNC_REF: main
