apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow-dev
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: git-sync-config
  - path: worker-replicas-patch.yaml
    target:
      kind: Deployment
      name: airflow-worker
  - path: api-server-replicas-patch.yaml
    target:
      kind: Deployment
      name: airflow-api-server
