apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-init
  namespace: airflow
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: airflow
      initContainers:
      - name: wait-for-postgres
        image: postgres:14-alpine
        command:
          - sh
          - -c
          - |
            until pg_isready -h airflow-postgres -p 5432; do
              echo "waiting for postgres..."
              sleep 3
            done
      containers:
        - name: airflow-init
          image: apache/airflow:3.0.6-python3.12
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          command:
            - bash
            - -ec
            - |
              airflow db migrate
              airflow fab-db migrate || true
              airflow users create \
                --username "$AIRFLOW_ADMIN_USERNAME" \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email "$AIRFLOW_ADMIN_EMAIL" \
                --password "$AIRFLOW_ADMIN_PASSWORD" || true
