apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - configmap.yaml
  - serviceaccount-rbac.yaml
  - pvc-postgres.yaml
  - postgres.yaml
  - redis.yaml
  - init.yaml
  - api-server.yaml
  - scheduler.yaml
  - dag-processor.yaml
  - worker.yaml
  - triggerer.yaml
# images:
#   - name: AIRFLOW_IMAGE
#     newName: ghcr.io/YOUR_ORG/airflow-custom
#     newTag: latest
