apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - configmap.yaml
  - rbac.yaml
  - postgres.yaml
  - redis.yaml
  - init.yaml
  - api-server.yaml
  - scheduler.yaml
  - dag-processor.yaml
  - worker.yaml
  - triggerer.yaml
  - pvc.yaml
images:
  - name: AIRFLOW_IMAGE
    newName: ghcr.io/21voidx/airflow-custom
    newTag: 3.0.6-python3.12