# Template only.
# File ini tidak dimasukkan ke kustomization base agar tidak otomatis ter-apply dengan placeholder.
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:CHANGE_ME@airflow-postgres:5432/airflow
  AIRFLOW__CELERY__BROKER_URL: redis://:CHANGE_ME@airflow-redis:6379/0
  AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:CHANGE_ME@airflow-postgres:5432/airflow
  AIRFLOW__CORE__FERNET_KEY: CHANGE_ME_FERNET_KEY
  AIRFLOW__API__SECRET_KEY: CHANGE_ME_API_SECRET
  AIRFLOW__API_AUTH__JWT_SECRET: CHANGE_ME_JWT_SECRET
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: CHANGE_ME_ADMIN_PASSWORD
  AIRFLOW_ADMIN_EMAIL: admin@example.com
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: CHANGE_ME_POSTGRES_PASSWORD
  POSTGRES_DB: airflow
  REDIS_PASSWORD: CHANGE_ME_REDIS_PASSWORD
